# Use the official Node.js 22.12.0 slim image as the base
FROM node:22.12.0-slim

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies, including PostgreSQL client
RUN apt-get update && apt-get install -y --no-install-recommends \
    dos2unix \
    openssl \
    libssl-dev \
    ca-certificates \
    file \
    bash \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install pnpm globally
RUN npm install -g pnpm

# Copy dependency definitions
COPY package*.json ./

# Install project dependencies
RUN pnpm install

# Copy the entire project code
COPY . .

# Convert entrypoint script to Unix format and make it executable
RUN dos2unix /app/scripts/docker-entrypoint.sh && \
    chmod +x /app/scripts/docker-entrypoint.sh

# Expose the desired port
EXPOSE 8080

# Define the entrypoint script
ENTRYPOINT ["/app/scripts/docker-entrypoint.sh"]

