version: '3.8'
services:
  database:
    image: postgres:15
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucherfaster
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - '5050:80'
    depends_on:
      - database

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: voucherfaster_server
    ports:
      - '${APP_PORT:-8080}:8080'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/voucherfaster?schema=public
    depends_on:
      - database
    env_file:
      - ./.env.development

volumes:
  postgres-data:
